const MORALIS_APP_ID = process.env.REACT_APP_MORALIS_APP_ID;
const MORALIS_SERVER_URL = process.env.REACT_APP_MORALIS_SERVER_URL;
const CONTRACT_ADDRESS = process.env.REACT_APP_CONTRACT_ADDRESS;
const CONTRACT_OWNER = process.env.REACT_APP_CONTRACT_OWNER;

const config = {
  MORALIS_APP_ID,
  MORALIS_SERVER_URL,
  CONTRACT_ADDRESS,
  CONTRACT_OWNER,
};

export default config;
